<hr style="border: 2px solid green;" />

Hello, Roman !🤚 

My name is Kseniya Vishnevskaya. I'm going to review your project 😊 

✏️You can find my comments in <font color='green'>green</font>, <font color='orange'>yellow</font> or <font color='red'>red</font> boxes like this:

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    I'm using green color if everything is done perfectly.</div>       
<br>
<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
    if I can give some recommendations</div>   
<br>
<div style="border:solid red 2px; padding: 20px"> <b>Needs fixing:</b><br>
    if the block requires some corrections. Work can't be accepted with the red comments</div>
 
Further in the file you can see my comments, try to take them into account when performing the next tasks. **Please, don't delete them.** :)

Let's work on the project in dialogue: if you change something in the project or respond to my comments, write about it. It will be easier for me to track the changes if you highlight your comments:

<div class="alert alert-info" style="border:solid blue 2px; padding: 20px"> <b>Student comment:</b> In the blue boxes you can leave comments and ask questions.</div>


<hr style="border: 2px solid green;" />

### <font color='orange'>General feedback</font>

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    Thank you for submitting your project 🙂  Wow! We reviewed your work, and it looks like a true A+. I especially liked the way you analysed the missing values, wrote your own functions and applying out-of-box approach in your research.  I've left some comments which could help you to improve your project and further develop your skills. Your project has been accepted!  Congratulations! 🥳 Good luck on the next sprint! </div>

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
    There are some comments for further improvement. They don't mean that you did anything wrong, but they're things we wanted to point out that can help you further develop your skills. 

And also I leave several links that can help you to make your further projects even better:

* Text formatting:
<a>https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd</a>

*  How to deal with missing values:
<a>https://towardsdatascience.com/how-to-deal-with-missing-data-in-python-1f74a9112d93</a>

*  How to edit text in jupyter notebook using Markdown:
<a>https://www.earthdatascience.org/courses/intro-to-earth-data-science/file-formats/use-text-files/format-text-with-markdown-jupyter-notebook/</a> 
    
   

<div class="alert alert-info" style="border:solid blue 2px; padding: 20px"> <b>Student comment:</b> Hi Kseniya, it's nice to meet you! Thank you so much for getting back this fast even though I was late on the soft deadline, and for your feedback, it really helped me feel motivated about this work! And thank you for leaving these amazing tips and links to new methods, I'll make sure to set aside some time and try all of them out! Really appreciate you taking the time to review my project. </div>
    

# Analyzing borrowers’ risk of defaulting

Your project is to prepare a report for a bank’s loan division. You’ll need to find out if a customer’s marital status and number of children has an impact on whether they will default on a loan. The bank already has some data on customers’ credit worthiness.

Your report will be considered when building a **credit scoring** of a potential customer. A ** credit scoring ** is used to evaluate the ability of a potential borrower to repay their loan.

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>

 Well done for adding the title and description of the project task :) But it is also important to include a description of the data to be worked with, like this:

 **Description of the data**

    
`children` - the number of children in the family
   
`days_employed` - how long the customer has been working
   
`dob_years` -  the customer’s age
   
`education` - the customer’s education level
 
etc.

And it is better to write the description in the form of a task. For example: "We need to find out if a customer’s marital status and number of children has an impact on whether they will default on a loan. Our report will be considered when building a credit scoring of a potential customer... etc. ". 
This is necessary because otherwise, the description sounds like you're giving the data to someone else to do the analysis.
    </div> 

## Open the data file and have a look at the general information. 

In [1]:
import pandas as pd

# reading the data and calling it *data* for simplicity
data = pd.read_csv('/Users/rv/Desktop/practice_datasets/credit_scoring_eng.csv')

# checking what it looks like
data.tail(10)


children  days_employed  dob_years            education  education_id  \
21515         1    -467.685130         28  secondary education             1   
21516         0    -914.391429         42    bachelor's degree             0   
21517         0    -404.679034         42    bachelor's degree             0   
21518         0  373995.710838         59  SECONDARY EDUCATION             1   
21519         1   -2351.431934         37      graduate degree             4   
21520         1   -4529.316663         43  secondary education             1   
21521         0  343937.404131         67  secondary education             1   
21522         1   -2113.346888         38  secondary education             1   
21523         3   -3112.481705         38  secondary education             1   
21524         2   -1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
21515            married                 0      F    employee     1   
21516            married                 0      F    business     0   
21517  civil partnership                 1      F    business     0   
21518            married                 0      F     retiree     0   
21519           divorced                 3      M    employee     0   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                     purpose  
21515     17517.812          to become educated  
21516     51649.244    purchase of my own house  
21517     28489.529           buying my own car  
21518     24618.344           purchase of a car  
21519     18551.846  buy commercial real estate  
21520     35966.698        housing transactions  
21521     24959.969           purchase of a car  
21522     14347.610                    property  
21523     39054.888           buying my own car  
21524     13127.587                to buy a car

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>

* **Best practice:** for convenience, it is common to keep all libraries used in code in a separate cell.
In future projects, the range of used libraries will expand, so it is more convenient if they are collected in one place. Please visit this link, there is a collection of interesting notebooks:

https://gist.github.com/ocoyawale/54d92fd4bf92508a2a6e482b5fa480fd
    
    
* The `describe()` function is very useful in getting to know the data. In this case, it looks much more indicative of the output is expanded by `df.describe().T`. In future projects, the `include` argument may come in handy - `df.describe(include = ['object']` is used to analyse categorical values.
    
</div>   

In [2]:
# checking out the general info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


Hmm. I think it's safe to change some things right off the bat: I'm going to rename column 'dob_years' to just 'age', since...that's what it tells us.

In [3]:
data = data.rename(columns = {'dob_years': 'age'})

#let's see that it works
data.head(10)

children  days_employed  age            education  education_id  \
0         1   -8437.673028   42    bachelor's degree             0   
1         1   -4024.803754   36  secondary education             1   
2         0   -5623.422610   33  Secondary Education             1   
3         3   -4124.747207   32  secondary education             1   
4         0  340266.072047   53  secondary education             1   
5         0    -926.185831   27    bachelor's degree             0   
6         0   -2879.202052   43    bachelor's degree             0   
7         0    -152.779569   50  SECONDARY EDUCATION             1   
8         2   -6929.865299   35    BACHELOR'S DEGREE             0   
9         0   -2188.756445   41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose  
0                purchase of the house  
1                         car purchase  
2                purchase of the house  
3              supplementary education  
4                    to have a wedding  
5                purchase of the house  
6                 housing transactions  
7                            education  
8                     having a wedding  
9  purchase of the house for my family

Nice.

### Looking at categorical values

Now, I just want to explore the data a little more to see what kind of different values it holds, and to get a sense of what I'll likely need to deal with in the sections ahead. I'll check the categorical values first, and will go on to check numerical values

In [4]:
data['education'].value_counts()

secondary education    13750
bachelor's degree       4718
SECONDARY EDUCATION      772
Secondary Education      711
some college             668
BACHELOR'S DEGREE        274
Bachelor's Degree        268
primary education        250
Some College              47
SOME COLLEGE              29
PRIMARY EDUCATION         17
Primary Education         15
graduate degree            4
Graduate Degree            1
GRADUATE DEGREE            1
Name: education, dtype: int64

OK, lots of renaming to do here later on.

In [5]:
data['education_id'].value_counts()

1    15233
0     5260
2      744
3      282
4        6
Name: education_id, dtype: int64

At a glance, this makes sense: most people will have finished secondary education, some less will hold a Bachelor's degree, still less people – only primary school or a master's degree. Afterwards, once I will have dealt with the values in 'education', I should be able to check that the numbers correspond to their correct names in that column.

In [6]:
data['family_status'].value_counts()

married              12380
civil partnership     4177
unmarried             2813
divorced              1195
widow / widower        960
Name: family_status, dtype: int64

This one actually looks good, at least there are no hidden duplicates like lower- and uppercase rendering of the same values. Although 'unmarried' doesn't really tell us if the person may be single or not (the pair may just not be into legalizing their relationship either in the form of marriage or civil partnership). So I might have to make a judgement call in the future if I want to categorize the data further by combining 'unmarried', 'divorced' and 'widow(er)' into a single category of singles as opposed to those in a relationship. 

In [7]:
data['family_status_id'].value_counts()

0    12380
1     4177
4     2813
3     1195
2      960
Name: family_status_id, dtype: int64

Looks good for now. (will need to do the same kind of work as with 'education_id' and 'education')

In [8]:
data['gender'].value_counts()

F      14236
M       7288
XNA        1
Name: gender, dtype: int64

Alright – again, no duplicates, lower and upper case F's and M's. So I googled XNA, and the few relevant search results that came up suggest that someone would fill this in if the value was missing. Indeed it seems like it couldn't be a result of a human/customer choice to, say, not state their gender or 'prefer not to say', because then there would probably be more than one.

In [9]:
data['income_type'].value_counts()

employee                       11119
business                        5085
retiree                         3856
civil servant                   1459
unemployed                         2
entrepreneur                       2
student                            1
paternity / maternity leave        1
Name: income_type, dtype: int64

This one raises some questions. For instance, the only 2 daring entrepreneurs suggest that maybe it shouldn't really be a category unto itself, but rather be part of 'business'? Maybe later we can investigate to see if there are any substantial differences between them – say, an entrepreneur could mean a big-shot investor, and business could mean a small business owner?

In [10]:
data['debt'].value_counts()

0    19784
1     1741
Name: debt, dtype: int64

Good, solvent citizens! Most of them.

In [11]:
data['purpose'].value_counts()

wedding ceremony                            797
having a wedding                            777
to have a wedding                           774
real estate transactions                    676
buy commercial real estate                  664
buying property for renting out             653
housing transactions                        653
transactions with commercial real estate    651
purchase of the house                       647
housing                                     647
purchase of the house for my family         641
construction of own property                635
property                                    634
transactions with my real estate            630
building a real estate                      626
buy real estate                             624
building a property                         620
purchase of my own house                    620
housing renovation                          612
buy residential real estate                 607
buying my own car                       

Lots of renaming and then combining to do here. Some will be tricky if we really need to differentiate between purchasing property for residential or commercial purposes, but we'll deal with that later.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    
I really like that you use <code>tail()</code>, `head()` `value_counts()` and <code>info()</code>  methods because they help you to see more information about the data you will work within your project. And thank you a lot for adding detailed conclusions 🙂   </div>

### Looking at quantitative values

In [12]:
data['children'].value_counts()

 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64

While having 20 children is not impossible, it's likely result of a typo (hitting that zero by mistake) in this case, especially because there aren't any number between 20 and 5 which is the next highest number of children, and this has to defy some laws of statistics... Also that -1 is probably a result of a technical error or typing in a hyphen for some reason. So maybe we can set it right by changing '20' to '2' and '-1' to '1'.

In [13]:
data.loc[data['children'] == 20, ['children']] = 2
data.loc[data['children'] == -1, ['children']] = 1

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>

  Yep, I agree with your decision to process the `children` column 👏 </div> 

In [14]:
# checking that it worked
data['children'].value_counts()

0    14149
1     4865
2     2131
3      330
4       41
5        9
Name: children, dtype: int64

Nice.

In [15]:
data['days_employed'].value_counts()

-8437.673028      1
-3507.818775      1
 354500.415854    1
-769.717438       1
-3963.590317      1
                 ..
-1099.957609      1
-209.984794       1
 398099.392433    1
-1271.038880      1
-1984.507589      1
Name: days_employed, Length: 19351, dtype: int64

OK, so days_employed is super tricky. Since it's not really pertinent to the project's task, I'm going to try to deal with it right here, and I will create a new column based on it so I can mess around with it. If it works out fine and I manage to fix it, in case there will be any missing values or duplicates, I will come back to those in the relevant section.

### *Dealing with days_employed*

So, first of all, the negative values – what's up with that?

In [16]:
data.loc[data['days_employed'] < 0].count()

children            15906
days_employed       15906
age                 15906
education           15906
education_id        15906
family_status       15906
family_status_id    15906
gender              15906
income_type         15906
debt                15906
total_income        15906
purpose             15906
dtype: int64

In [17]:
data.loc[data['days_employed'] < 0].count() / len(data)

children            0.738955
days_employed       0.738955
age                 0.738955
education           0.738955
education_id        0.738955
family_status       0.738955
family_status_id    0.738955
gender              0.738955
income_type         0.738955
debt                0.738955
total_income        0.738955
purpose             0.738955
dtype: float64

OK, so close to 74% of the values in days_employed are negative, for whatever reason. My best bet is that this is a result of a technical error of some kind, maybe when exporting that data from another programme. Let's create a new column and turn these values to absolute

In [18]:
data['abs_days_employed'] = data['days_employed'].abs()

#checking that it worked
data.head(10)

children  days_employed  age            education  education_id  \
0         1   -8437.673028   42    bachelor's degree             0   
1         1   -4024.803754   36  secondary education             1   
2         0   -5623.422610   33  Secondary Education             1   
3         3   -4124.747207   32  secondary education             1   
4         0  340266.072047   53  secondary education             1   
5         0    -926.185831   27    bachelor's degree             0   
6         0   -2879.202052   43    bachelor's degree             0   
7         0    -152.779569   50  SECONDARY EDUCATION             1   
8         2   -6929.865299   35    BACHELOR'S DEGREE             0   
9         0   -2188.756445   41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose  abs_days_employed  
0                purchase of the house        8437.673028  
1                         car purchase        4024.803754  
2                purchase of the house        5623.422610  
3              supplementary education        4124.747207  
4                    to have a wedding      340266.072047  
5                purchase of the house         926.185831  
6                 housing transactions        2879.202052  
7                            education         152.779569  
8                     having a wedding        6929.865299  
9  purchase of the house for my family        2188.756445

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    
  Really great that you processed negative values using `abs()` method. And displayed the percentages of negative values before processing them. 🤩 

There it is, the good twin. (to the right)

Let's get a closer look:

In [19]:
data['abs_days_employed'].describe()

count     19351.000000
mean      66914.728907
std      139030.880527
min          24.141633
25%         927.009265
50%        2194.220567
75%        5537.882441
max      401755.400475
Name: abs_days_employed, dtype: float64

Huh?

In [20]:
data['abs_days_employed'].describe()/365

count      53.016438
mean      183.328024
std       380.906522
min         0.066141
25%         2.539751
50%         6.011563
75%        15.172281
max      1100.699727
Name: abs_days_employed, dtype: float64

And there is the obvious problem that some people literally had to work inhumane hours to get this dataset's average to 183 years of employment. And the problem is not solved by dividing the values further, say, by 24 hours, if we choose to make this assumption about the origin of this data:

In [21]:
data['abs_days_employed'].describe()/365/24

count     2.209018
mean      7.638668
std      15.871105
min       0.002756
25%       0.105823
50%       0.250482
75%       0.632178
max      45.862489
Name: abs_days_employed, dtype: float64

The numbers still don't make any sense, and besides, the huge difference between the mean and the median values tells us that there are indeed a number of values that just have to be abnormally high.

Looking at the data, I don't see an obvious extra triple zero before the dot, and these values seem to belong to observations of people with different values in other columns, such as income, age and so on. They are spread out across the dataset. But they are associated with one income_type though: retirees. Furthermore, looking once more at the original days_employed column, I can see that all the values in the normal range seem to have that minus sign, whereas the insanely high values are all positive.

In [22]:
data[2750:2800]

children  days_employed  age            education  education_id  \
2750         1    -576.507060   44  secondary education             1   
2751         0   -1265.408556   53  secondary education             1   
2752         1    -327.014944   25  secondary education             1   
2753         0  332207.706723   58  secondary education             1   
2754         0    -241.900929   36  SECONDARY EDUCATION             1   
2755         0   -3828.034774   46  secondary education             1   
2756         2   -1277.265112   37         some college             2   
2757         0   -1308.144973   21    bachelor's degree             0   
2758         0   -2847.503085   44    bachelor's degree             0   
2759         1   -1164.233151   39  secondary education             1   
2760         0  374578.065311   55  secondary education             1   
2761         0    -394.340470   48  secondary education             1   
2762         1   -1190.159840   48  secondary education             1   
2763         0            NaN   59  secondary education             1   
2764         1   -3421.220659   33    Bachelor's Degree             0   
2765         0    -995.549652   43  secondary education             1   
2766         1   -3285.726873   27  secondary education             1   
2767         2    -926.394995   35    bachelor's degree             0   
2768         1            NaN   48    Bachelor's Degree             0   
2769         2   -1351.514078   40  secondary education             1   
2770         0   -2514.545359   28    bachelor's degree             0   
2771         0  366906.639791   55  secondary education             1   
2772         0   -1483.177789   42  secondary education             1   
2773         0   -5505.152447   60    bachelor's degree             0   
2774         2   -3231.940870   39  SECONDARY EDUCATION             1   
2775         0   -1453.211233   32    BACHELOR'S DEGREE             0   
2776         1    -669.396447   27    bachelor's degree             0   
2777         0  343480.870183   53  SECONDARY EDUCATION             1   
2778         1    -106.155252   47  SECONDARY EDUCATION             1   
2779         0   -2922.866017   27    bachelor's degree             0   
2780         0  397336.081456   64  Secondary Education             1   
2781         0  383300.062576   54  secondary education             1   
2782         0  348232.256296   50  secondary education             1   
2783         1   -1702.357343   49  secondary education             1   
2784         1   -2766.243884   34  secondary education             1   
2785         0    -900.044514   30  secondary education             1   
2786         0            NaN   51  secondary education             1   
2787         0  329182.845157   54    bachelor's degree             0   
2788         0  375045.287317   57    bachelor's degree             0   
2789         0  376924.294696   61    bachelor's degree             0   
2790         0   -2676.977539   45    bachelor's degree             0   
2791         0    -679.136080   50  secondary education             1   
2792         3   -1795.252264   39  secondary education             1   
2793         0   -1172.188652   24         some college             2   
2794         0   -4164.518916   48  secondary education             1   
2795         0  365882.588529   67  secondary education             1   
2796         0    -754.732096   42    bachelor's degree             0   
2797         2   -4908.553231   37    bachelor's degree             0   
2798         0  354704.197608   54  secondary education             1   
2799         0  384408.937734   62  secondary education             1   

          family_status  family_status_id gender    income_type  debt  \
2750            married                 0      M       employee     1   
2751            married                 0      F       employee     0   
2752            married                 0      M       employee

Assuming that these are indeed just insane values that have happened by mistake, what if there is a threshold we could take to isolate them? Let's try 30000, which is approximately 82 years, the highest imaginable number, if we assume (at a stretch) that someone started working at 18 and managed to stay employed into their 100's.

In [23]:
data[data['abs_days_employed'] > 30000].describe()

children  days_employed          age  education_id  \
count  3445.000000    3445.000000  3445.000000   3445.000000   
mean      0.095791  365004.309916    59.124819      0.914659   
std       0.338400   21075.016396     7.580584      0.517103   
min       0.000000  328728.720605     0.000000      0.000000   
25%       0.000000  346639.413916    56.000000      1.000000   
50%       0.000000  365213.306266    60.000000      1.000000   
75%       0.000000  383246.444219    64.000000      1.000000   
max       4.000000  401755.400475    74.000000      4.000000   

       family_status_id         debt   total_income  abs_days_employed  
count       3445.000000  3445.000000    3445.000000        3445.000000  
mean           0.984325     0.052830   21939.856893      365004.309916  
std            1.316071     0.223727   12838.753752       21075.016396  
min            0.000000     0.000000    3306.762000      328728.720605  
25%            0.000000     0.000000   13260.214000      346639.413916  
50%            0.000000     0.000000   18962.318000      365213.306266  
75%            2.000000     0.000000   27159.402000      383246.444219  
max            4.000000     1.000000  117616.523000      401755.400475

OK, so we can see that this is indeed a kind of a subset with a minimum insane number of days starting at 328728 (or 900 years) and going up to a max of 401755 (or 1100 years). Let's take a look at the 'normal' values:

In [24]:
data[data['abs_days_employed'] < 30000].describe()

children  days_employed           age  education_id  \
count  15906.000000   15906.000000  15906.000000  15906.000000   
mean       0.562744   -2353.015932     39.818245      0.798378   
std        0.792367    2304.243851     10.663171      0.554845   
min        0.000000  -18388.949901      0.000000      0.000000   
25%        0.000000   -3157.480084     32.000000      0.000000   
50%        0.000000   -1630.019381     39.000000      1.000000   
75%        1.000000    -756.371964     48.000000      1.000000   
max        5.000000     -24.141633     75.000000      4.000000   

       family_status_id          debt   total_income  abs_days_employed  
count      15906.000000  15906.000000   15906.000000       15906.000000  
mean           0.969634      0.087326   27837.509634        2353.015932  
std            1.442263      0.282320   16980.846677        2304.243851  
min            0.000000      0.000000    3418.824000          24.141633  
25%            0.000000      0.000000   17323.415000         756.371964  
50%            0.000000      0.000000   24181.535000        1630.019381  
75%            1.000000      0.000000   33839.106500        3157.480084  
max            4.000000      1.000000  362496.645000       18388.949901

Indeed, now we see that the actual highest number of days in employment is 18388, which is roughly 50 years: an honest (and realistic) life's work. The mean and the median values are not as far apart anymore, too. One more thing: we can see that the number of these 'normal' values is the same as the number of negative values (15906), which we saw before when doing a count of values < 0. So it's confirmed: all the values in the normal range seem to have been exported as negatives, whereas the abnormally high values came positive.

In [25]:
data[data['abs_days_employed'] > 30000]['income_type'].unique()

array(['retiree', 'unemployed'], dtype=object)

In [26]:
data[data['income_type'] == 'retiree']['days_employed'].value_counts()

340266.072047    1
349012.164686    1
332278.816712    1
361424.440523    1
385741.351317    1
                ..
352708.834270    1
378067.765448    1
368375.356113    1
341888.992230    1
343937.404131    1
Name: days_employed, Length: 3443, dtype: int64

And indeed, as we saw before these numbers only happen (mostly) to the retirees for some reason. But not to all of them. In the table of insane days_employed numbers we can see that there are 3445 rows with them, whereas the total number of retirees is 3856. So what if that applies to all the retirees, except for those with missing values in days_employed?

In [27]:
data.loc[data['days_employed'].isnull()]['income_type'].value_counts()

employee         1105
business          508
retiree           413
civil servant     147
entrepreneur        1
Name: income_type, dtype: int64

Indeed that seems to be the case. And what if the values for retirees came recorded in hours instead of days? It looks like if we apply that inititial treatment of dividing the values in days_employed by 24 hours ONLY to retirees (and the 2 unemployed), the numbers will actually make sense. Dividing by 365 just to see the value in years

In [28]:
data[data['abs_days_employed'] > 30000].describe()/365/24

children  days_employed       age  education_id  family_status_id  \
count  0.393265       0.393265  0.393265      0.393265          0.393265   
mean   0.000011      41.667159  0.006749      0.000104          0.000112   
std    0.000039       2.405824  0.000865      0.000059          0.000150   
min    0.000000      37.526110  0.000000      0.000000          0.000000   
25%    0.000000      39.570709  0.006393      0.000114          0.000000   
50%    0.000000      41.691017  0.006849      0.000114          0.000000   
75%    0.000000      43.749594  0.007306      0.000114          0.000228   
max    0.000457      45.862489  0.008447      0.000457          0.000457   

           debt  total_income  abs_days_employed  
count  0.393265      0.393265           0.393265  
mean   0.000006      2.504550          41.667159  
std    0.000026      1.465611           2.405824  
min    0.000000      0.377484          37.526110  
25%    0.000000      1.513723          39.570709  
50%    0.000000      2.164648          41.691017  
75%    0.000000      3.100388          43.749594  
max    0.000114     13.426544          45.862489

Indeed, now these values look reasonable especially: a minimum number of days employed expressed in years is 37, and the maximum is 45 years. This seems like the right range of values for 'retiree' category.

So let's replace the faulty data with the correct values, in the experimental abs_days_employed columns for starters, and look at the resulting stats. If everything looks good, we can fix the original days_employed column.

In [29]:
new_data = data[data['abs_days_employed'] > 30000]['abs_days_employed']/24
data.loc[data['abs_days_employed'] > 30000, ['abs_days_employed']] = new_data

In [30]:
data[data['income_type'] == 'retiree']['abs_days_employed'].describe()/365

count     9.432877
mean     41.667065
std       2.405206
min      37.526110
25%      39.571843
50%      41.691017
75%      43.747876
max      45.862489
Name: abs_days_employed, dtype: float64

In [31]:
data['abs_days_employed'].describe()

count    19351.000000
mean      4641.641176
std       5355.964289
min         24.141633
25%        927.009265
50%       2194.220567
75%       5537.882441
max      18388.949901
Name: abs_days_employed, dtype: float64

Looks better! I guess we can repair the original days_employed column now, and the simplest way to do so is to assign to it the values in abs_days_employed. Then we can get rid of the abs_days_employed.

In [32]:
data['days_employed'] = data['abs_days_employed']

In [33]:
data['days_employed'].describe()

count    19351.000000
mean      4641.641176
std       5355.964289
min         24.141633
25%        927.009265
50%       2194.220567
75%       5537.882441
max      18388.949901
Name: days_employed, dtype: float64

In [34]:
data.drop(columns = 'abs_days_employed', inplace = True)

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
   
 When you write this code: `data['days_employed'] = data['abs_days_employed']` you basically make the column  
`days_employed` column is referenced to the `abs_days_employed` column. After you delete the `abs_days_employed` column, the `days_employed` column is no longer referenced to it and has the old values with gaps again. The solution to this problem: delete the `days_employed` column and then rename the `abs_days_employed` column to `days_employed` using the `rename()` method

</div>
 

In [35]:
#Reviewer's code
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   age               21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


In [36]:
data.head(15) # checking to see that the extra column is gone

children  days_employed  age            education  education_id  \
0          1    8437.673028   42    bachelor's degree             0   
1          1    4024.803754   36  secondary education             1   
2          0    5623.422610   33  Secondary Education             1   
3          3    4124.747207   32  secondary education             1   
4          0   14177.753002   53  secondary education             1   
5          0     926.185831   27    bachelor's degree             0   
6          0    2879.202052   43    bachelor's degree             0   
7          0     152.779569   50  SECONDARY EDUCATION             1   
8          2    6929.865299   35    BACHELOR'S DEGREE             0   
9          0    2188.756445   41  secondary education             1   
10         2    4171.483647   36    bachelor's degree             0   
11         0     792.701887   40  secondary education             1   
12         0            NaN   65  secondary education             1   
13         0    1846.641941   54         some college             2   
14         0    1844.956182   56    bachelor's degree             0   

        family_status  family_status_id gender income_type  debt  \
0             married                 0      F    employee     0   
1             married                 0      F    employee     0   
2             married                 0      M    employee     0   
3             married                 0      M    employee     0   
4   civil partnership                 1      F     retiree     0   
5   civil partnership                 1      M    business     0   
6             married                 0      F    business     0   
7             married                 0      M    employee     0   
8   civil partnership                 1      F    employee     0   
9             married                 0      M    employee     0   
10            married                 0      M    business     0   
11            married                 0      F    employee     0   
12  civil partnership                 1      M     retiree     0   
13            married                 0      F    employee     0   
14  civil partnership                 1      F    business     1   

    total_income                              purpose  
0      40620.102                purchase of the house  
1      17932.802                         car purchase  
2      23341.752                purchase of the house  
3      42820.568              supplementary education  
4      25378.572                    to have a wedding  
5      40922.170                purchase of the house  
6      38484.156                 housing transactions  
7      21731.829                            education  
8      15337.093                     having a wedding  
9      23108.150  purchase of the house for my family  
10     18230.959                      buy real estate  
11     12331.077           buy commercial real estate  
12           NaN                    to have a wedding  
13     20873.317                         car purchase  
14     26420.466          buy residential real estate

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   age               21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


Phew! It worked.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
 It's important to process <code>days_employed</code> column. There are firstly many abnormally high values, and secondly negative values. It's great that you noticed this and used your own methods to process them 🔥  Thank you for your bright idea!</div> 

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
  
How else could this problem still be solved:

    
* Roughly calculate how many maximum years the person could work to his current age (if he is 60 years old, then 60-18=42 years). The working days are approximately 257. 257*42=10794 days at most could work in his lifetime. Think of a conditional error, let it be 1000 (if let's say he is a workaholic and worked all the time or started working at an earlier age. 10794 + 1000 = 11794. Compare this number with the value in the `days_employed` column. If 11794 < days_employed, fill in NaN. Then fill in the missing values with the median `days_employed`, grouping by `dob_years`.

* Assume what the maximum `days_employed`  is possible based on age (by estimating how many days per year a person works) and replace all abnormally high values simply by the maximum possible `days_employed` for each person. Suppose the person is 60 years old. Then he can have a maximum length of service of 60-18=42 years. And for a person 20 years old, the maximum length of service is 2 years. Then we fill in their `days_employed`with these values.

</div>

In [38]:
#problem_entries = []

#for value in data['abs_days_employed']:
#    try:
#        value = int(value)
#    except:
#        problem_entries.append(value)

#print(problem_entries)

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
    If you are not going to use this code in the future, it is better to delete it.</div>  

### *MOVING ON*

In [39]:
data['age'].describe()

count    21525.000000
mean        43.293380
std         12.574584
min          0.000000
25%         33.000000
50%         42.000000
75%         53.000000
max         75.000000
Name: age, dtype: float64

Hmmm

In [40]:
data.loc[data['age'] == 0]

children  days_employed  age            education  education_id  \
99            0   14439.234121    0  Secondary Education             1   
149           0    2664.273168    0  secondary education             1   
270           3    1872.663186    0  secondary education             1   
578           0   16577.356876    0  secondary education             1   
1040          0    1158.029561    0    bachelor's degree             0   
...         ...            ...  ...                  ...           ...   
19829         0            NaN    0  secondary education             1   
20462         0   14113.952856    0  secondary education             1   
20577         0   13822.552977    0  secondary education             1   
21179         2     108.967042    0    bachelor's degree             0   
21313         0    1268.487728    0  secondary education             1   

      family_status  family_status_id gender income_type  debt  total_income  \
99          married                 0      F     retiree     0     11406.644   
149        divorced                 3      F    employee     0     11228.230   
270         married                 0      F    employee     0     16346.633   
578         married                 0      F     retiree     0     15619.310   
1040       divorced                 3      F    business     0     48639.062   
...             ...               ...    ...         ...   ...           ...   
19829       married                 0      F    employee     0           NaN   
20462       married                 0      F     retiree     0     41471.027   
20577     unmarried                 4      F     retiree     0     20766.202   
21179       married                 0      M    business     0     38512.321   
21313     unmarried                 4      M    employee     0     24387.070   

                            purpose  
99                              car  
149            housing transactions  
270              housing renovation  
578    construction of own property  
1040                   to own a car  
...                             ...  
19829                       housing  
20462      purchase of my own house  
20577                      property  
21179        building a real estate  
21313          housing transactions  

[101 rows x 12 columns]

So we have some 101 missing values – people aged zero, some divorced, some already retired... No idea what to do with them right off the bat, but then they won't really affect our analysis. If needed, we could fill them in with smth like median values depending on their income type.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
 Or just remove them if the percentage of incorrect data is small :)</div>       

In [41]:
data['total_income'].describe()

count     19351.000000
mean      26787.568355
std       16475.450632
min        3306.762000
25%       16488.504500
50%       23202.870000
75%       32549.611000
max      362496.645000
Name: total_income, dtype: float64

In [42]:
data.isnull().sum()

children               0
days_employed       2174
age                    0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

The data under 'total_income' looks good, only there are 2174 missing values. Let's see what they look like:

In [43]:
data.loc[data['total_income'].isnull()]['total_income']

12      NaN
26      NaN
29      NaN
41      NaN
55      NaN
         ..
21489   NaN
21495   NaN
21497   NaN
21502   NaN
21510   NaN
Name: total_income, Length: 2174, dtype: float64

It seems entirely reasonable that there would be a number of people without an income to declare. Indeed, let's take a look – it's quite possible these are the same people who didn't put down any days employed.

In [44]:
data.loc[(data['days_employed'].isnull()) & (data['total_income'].isnull())].count()

children            2174
days_employed          0
age                 2174
education           2174
education_id        2174
family_status       2174
family_status_id    2174
gender              2174
income_type         2174
debt                2174
total_income           0
purpose             2174
dtype: int64

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
 Well done for using condition in the slice to see if the <code>days_employed</code> column and the <code>total_income</code> column have missing values in the same rows 😻  </div>

Well, it could make sense. Maybe we can convert these NaNs to zeroes later – or maybe not.

In [45]:
data.loc[data['total_income'].isnull()]['income_type'].value_counts()

employee         1105
business          508
retiree           413
civil servant     147
entrepreneur        1
Name: income_type, dtype: int64

This is more of a mystery. Perhaps this is their first day of work? More likely not. It looks like it would make more sense to fill these in after all, according to their income type.

### Conclusion

Just looking at the data, we can see that there is some work to be done in order to bring some of the categorical values in order (different casings and spellings for values in 'education', 'purpose' and other columns. Some are OK, like 'family_status' or 'gender' (except for only one entry that says 'XNA')). 

Days_employed is pretty messed up, but we managed to deal with it.

The number of missing values in total_income is the same as in days employed which, on first glance, could mean those are not a result of a technical/formatting or human error, but that they simply reflect the reality – people who were never employed could not declare any income. Indeed we can verify that they occur in the same rows. However, we also see that those people appear to be employed in various capacities, so that's weird. It's more likely that we need to restore them after all.

I would also argue that we could change the data type for the number of days employed to integer – there isn't any point in having those with precision to the number of seconds employed. I wonder how those values could appear in the first place. Perhaps they were first calculated by the bank's programme from some other data, for instance by substracting first day of employment from a datetime item that was in turn formatted to the second, without using the days attribute, and converted to float.

<div style="border:solid green 2px; padding: 20px"> <b>Success :</b><br>
   I like that you wrote such in-depth conclusions and made logical assumptions.  It's really great! 👏👏👏</div> 

## Data preprocessing

### Processing missing values

In [46]:
data.isnull().sum()

children               0
days_employed       2174
age                    0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

OK, so we have the glaring missing values in the two columns, which, as we know, belong to the same rows. But first, remember that there were the not-so obvious zeroes in the 'age' column (since they're not NaN, they are just read as normal quantitative values and are not flagged by isnull()). Let me deal with them first.

### Filling in missing values in 'age'

In [47]:
data['age'].isnull().sum()

0

Nothing to see here. Or is there? -_-

In [48]:
data.loc[data['age'] == 0].count()

children            101
days_employed        91
age                 101
education           101
education_id        101
family_status       101
family_status_id    101
gender              101
income_type         101
debt                101
total_income         91
purpose             101
dtype: int64

Here they, zero years old. Let's convert them into Nones, so that we can fill them in later.

In [49]:
data.loc[data['age'] == 0, ['age']] = None

In [50]:
data['age'].isnull().sum()

101

Now the isnull() picks them up as missing values

What should we fill them with? I would argue that it makes the most sense to go for the mean or median age according their income_type, since this is the parameter that seems to correlate with different ages best of all.

In [51]:
# Let's see the breakdown of missing values by income_type
data.loc[data['age'].isnull()]['income_type'].value_counts()

employee         55
retiree          20
business         20
civil servant     6
Name: income_type, dtype: int64

Let's see what the mean and the median look like for these

In [52]:
data.groupby('income_type')['age'].mean()

income_type
business                       39.854294
civil servant                  40.804542
employee                       40.018980
entrepreneur                   42.500000
paternity / maternity leave    39.000000
retiree                        59.370959
student                        22.000000
unemployed                     38.000000
Name: age, dtype: float64

In [53]:
data.groupby('income_type')['age'].median()

income_type
business                       39.0
civil servant                  40.0
employee                       39.0
entrepreneur                   42.5
paternity / maternity leave    39.0
retiree                        60.0
student                        22.0
unemployed                     38.0
Name: age, dtype: float64

Doesn't look like a massive difference. I would also suggest looking at gender differences, since, as we know from the start, female customers constitute the majority in this dataset. So if we were to take median values without accounting for the gender, this would skew the results.

In [54]:
data.groupby(['income_type', 'gender'])['age'].mean()

income_type                  gender
business                     F         40.181904
                             M         39.308347
                             XNA       24.000000
civil servant                F         41.588400
                             M         38.622396
employee                     F         40.471492
                             M         39.305543
entrepreneur                 F         27.000000
                             M         58.000000
paternity / maternity leave  F         39.000000
retiree                      F         59.459382
                             M         58.972740
student                      M         22.000000
unemployed                   F         45.000000
                             M         31.000000
Name: age, dtype: float64

In [55]:
data.groupby(['income_type', 'gender'])['age'].median()

income_type                  gender
business                     F         40.0
                             M         38.0
                             XNA       24.0
civil servant                F         41.0
                             M         37.0
employee                     F         40.0
                             M         38.0
entrepreneur                 F         27.0
                             M         58.0
paternity / maternity leave  F         39.0
retiree                      F         60.0
                             M         60.0
student                      M         22.0
unemployed                   F         45.0
                             M         31.0
Name: age, dtype: float64

It's quite a median difference in age – 1 years for employees, and 4 years for civil servants. It's best that we account for that. It may not do much difference for the missing values in age, since there are only 101 of them, but it's good practice and would definitely be advisable when dealing with larger numbers.

It's not a massive difference for mean and median, but let us go ahead and replace the missing values with the median, just to be on the safe side.

In [56]:
categories_with_missing_values = ['employee', 'business', 'retiree', 'civil servant']
genders = ['F', 'M']

for gender in genders:
    for cat in categories_with_missing_values:
        cat_median_age = data.loc[(data['income_type'] == cat) & (data['gender'] == gender)]['age'].median()
        data.loc[(data['income_type'] == cat) & (data['gender'] == gender), 'age'] = data['age'].fillna(cat_median_age)

Let us check to see that it worked:

In [57]:
data['age'].isnull().sum()

0

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
     
 Thank you for using your own function to process  `age`  column!
But the functions can sometimes overload code and slow it down. That's why it's better not to use functions where you can do without them, for example your code can be written like this: <code> data['age'] = data['age'].fillna(data.groupby(['income_type', 'gender'])['age'].transform('median'))</code>

`transform()` method is very useful for such type of cases :)
</div>   

We can also check that it hasn't distorted the resulting stats:

In [58]:
data.groupby(['income_type', 'gender'])['age'].median()

income_type                  gender
business                     F         40.0
                             M         38.0
                             XNA       24.0
civil servant                F         41.0
                             M         37.0
employee                     F         40.0
                             M         38.0
entrepreneur                 F         27.0
                             M         58.0
paternity / maternity leave  F         39.0
retiree                      F         60.0
                             M         60.0
student                      M         22.0
unemployed                   F         45.0
                             M         31.0
Name: age, dtype: float64

Looks good! Well, we can't really see any difference, since the values we filled in are about 0,5% to the total number of values, but since we filled them in line with the median values per gender and income_type, this is the result we should expect.

### Filling in missing values for 'days_employed'

We've seen that the missing values for days_employed occur in the same rows as total_income, which could have a logical explanation that people who have never been employed declare zero income. But then a) why would they hope for applying for a loan at a bank? b) why would they be listed as employed in various capacities? More likely, these are properly missing values that should be restored.

In [59]:
data.loc[data['days_employed'].isnull()]['debt'].sum()

170

Still more reason to restore the missing values as opposed to just dropping the rows, for example – is because this subset of rows accounts for about 10% of all people who have previously defaulted on their loans (over 1700). So removing them completely would skew the data.

I would suggest to restore the values by inserting median values, based on age, gender and income type, as these seem to be the most pertinent for suggesting the number of days_employed. For example, below we can see how females seem to have a few less recorded days than males, and we could make a plausible assumption that this be due to maternity leave. Since females are the majority in our dataset, we should definitely account for gender. Income_type matters, too: we can see major differences on average for various occupations. And age is pretty much self-explanatory.

In [60]:
data.groupby(['age', 'gender', 'income_type'])['days_employed'].mean()

age   gender  income_type  
19.0  F       business           594.033329
              civil servant      509.969922
              employee           715.476909
      M       business           111.762790
              employee           952.725852
                                   ...     
74.0  F       employee          6682.867814
              retiree          15201.939127
      M       business          1729.632531
              retiree          14359.326504
75.0  F       civil servant     1678.969771
Name: days_employed, Length: 410, dtype: float64

In [61]:
data.groupby(['age', 'gender', 'income_type'])['days_employed'].median()

age   gender  income_type  
19.0  F       business           710.230781
              civil servant      509.969922
              employee           793.358581
      M       business           111.762790
              employee           952.725852
                                   ...     
74.0  F       employee          6682.867814
              retiree          15535.879332
      M       business          1729.632531
              retiree          14359.326504
75.0  F       civil servant     1678.969771
Name: days_employed, Length: 410, dtype: float64

We can see some difference (in this small subset) for young females whose income_type is business, so let's go with the median values.

In [62]:
ages = data['age'].unique()
genders = ['F', 'M']
income_types = ['employee', 'business', 'retiree', 'civil servant', 'entrepreneur']

for a in ages:
    for g in genders:
        for i in income_types:
            median_d = data.loc[(data['age'] == a) & (data['gender'] == g) & (data['income_type'] == i)]['days_employed'].median()
            data.loc[(data['age'] == a) & (data['gender'] == g) & (data['income_type'] == i), 'days_employed'] = data['days_employed'].fillna(median_d)

In [63]:
# Let's see if it worked:
data.isna().sum()

children               0
days_employed          5
age                    0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

Hmm. Let's see why it didn't work for 5 rows.

In [64]:
data.loc[data['days_employed'].isna()]

children  days_employed   age            education  education_id  \
3619          0            NaN  24.0  secondary education             1   
5936          0            NaN  58.0    bachelor's degree             0   
17374         0            NaN  69.0    bachelor's degree             0   
18175         2            NaN  31.0  secondary education             1   
18255         0            NaN  38.0  secondary education             1   

           family_status  family_status_id gender   income_type  debt  \
3619             married                 0      F       retiree     0   
5936             married                 0      M  entrepreneur     0   
17374          unmarried                 4      F      business     0   
18175  civil partnership                 1      F       retiree     0   
18255  civil partnership                 1      M       retiree     0   

       total_income                      purpose  
3619            NaN     purchase of my own house  
5936            NaN  buy residential real estate  
17374           NaN                         cars  
18175           NaN             wedding ceremony  
18255           NaN            profile education

In [65]:
data.loc[(data['age'] == 24.0) & (data['gender'] == 'F') & (data['income_type'] == 'retiree')]

children  days_employed   age            education  education_id  \
3619         0            NaN  24.0  secondary education             1   

     family_status  family_status_id gender income_type  debt  total_income  \
3619       married                 0      F     retiree     0           NaN   

                       purpose  
3619  purchase of my own house

Looks like we conditions in my function were too strict for these five entries: as we see above, there were no similar rows for them that contained a day_employed value, so nothing to make a median value from. It would be best to tweak the function a little bit to account for such cases, so let me try to do it below. I would argue that for these 5 cases we can base the median value on age and gender, excluding the income_type. The reason for that is that for some combinations of age and gender, there is only one person of a certain income_type (like with that 24-y.o. retiree, which in itself is interesting). And then, for entrepreneur, there are only two entries in total.

In [66]:
ages = data['age'].unique()
genders = ['F', 'M']
income_types = ['employee', 'business', 'retiree', 'civil servant', 'entrepreneur']

for a in ages:
    for g in genders:
        for i in income_types:
            if len(data.loc[(data['age'] == a) & (data['gender'] == g) & (data['income_type'] == i)]['days_employed']) > 1:
                median_d = data.loc[(data['age'] == a) & (data['gender'] == g) & (data['income_type'] == i)]['days_employed'].median()
                data.loc[(data['age'] == a) & (data['gender'] == g) & (data['income_type'] == i), 'days_employed'] = data['days_employed'].fillna(median_d)
            else:
                median_d = data.loc[(data['age'] == a) & (data['gender'] == g)]['days_employed'].median()
                data.loc[(data['age'] == a) & (data['gender'] == g), 'days_employed'] = data['days_employed'].fillna(median_d)

In [67]:
data.isna().sum()

children               0
days_employed          0
age                    0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

Alright! Let's just make sure that those 5 rows have plausible days_employed values now:

In [68]:
data.loc[[3619, 5936, 17374, 18175, 18255]]

children  days_employed   age            education  education_id  \
3619          0     991.631441  24.0  secondary education             1   
5936          0    4136.913687  58.0    bachelor's degree             0   
17374         0   15170.172432  69.0    bachelor's degree             0   
18175         2    1312.368018  31.0  secondary education             1   
18255         0    1577.257358  38.0  secondary education             1   

           family_status  family_status_id gender   income_type  debt  \
3619             married                 0      F       retiree     0   
5936             married                 0      M  entrepreneur     0   
17374          unmarried                 4      F      business     0   
18175  civil partnership                 1      F       retiree     0   
18255  civil partnership                 1      M       retiree     0   

       total_income                      purpose  
3619            NaN     purchase of my own house  
5936            NaN  buy residential real estate  
17374           NaN                         cars  
18175           NaN             wedding ceremony  
18255           NaN            profile education

Looks good!

### Filling in missing values for 'gender'

As we saw previously, our built-in methods didn't pick up on any 'standard' missing values in the gender column, but we can spot one 'XNA' value.

In [69]:
data['gender'].value_counts()

F      14236
M       7288
XNA        1
Name: gender, dtype: int64

Let's have a closer look

In [70]:
data.loc[data['gender'] == 'XNA']

children  days_employed   age     education  education_id  \
10701         0    2358.600502  24.0  some college             2   

           family_status  family_status_id gender income_type  debt  \
10701  civil partnership                 1    XNA    business     0   

       total_income          purpose  
10701     32624.825  buy real estate

So we can see that this is someone who has started working at a relatively young age, received some college education, and likely runs their own business making a decent total income, whilst being in a civil partnership. XNA is a standard for marking a missing gender value as unknown. It is unlikely to be a case of someone consciously refusing to state their gender or choosing 'prefer not to say', because in that case there would likely be more than a single XNA. However, it seems to me that in this particular case it is unnecessary to try to fill in the missing value, since there is nothing to really give us a clue one way or the other regarding the person's gender. Since it is just one value, and doesn't really affect our project's task, I would simply leave it as it is.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    It's very good that you found gender <code>XNA</code> in our data  👍 we can just delete this row :)</div>       
<br>

### Filling in missing values for 'total_income'

As far as I can see, total_income reflects yearly income – and the value range certainly looks realistic if it reflected data from a European city (maybe a bit low for the U.S. or the UK). In that case, I'd argue it would be best not to consider days_employed and age as factor, but rather stick to gender and income_type.

In [71]:
data.groupby(['gender', 'income_type']).agg({'total_income': ['mean', 'median']})

total_income            
                                            mean      median
gender income_type                                          
F      business                     29475.489877  25731.3245
       civil servant                24908.849830  21917.1980
       employee                     23818.105441  20898.4980
       entrepreneur                 79866.103000  79866.1030
       paternity / maternity leave   8612.661000   8612.6610
       retiree                      21446.167378  18529.2465
       unemployed                   32435.602000  32435.6020
M      business                     37284.334474  31491.0080
       civil servant                34036.170503  29754.3915
       employee                     28956.563225  25945.7880
       entrepreneur                          NaN         NaN
       retiree                      24117.476626  20918.3620
       student                      15712.260000  15712.2600
       unemployed                    9593.119000   9593.1190
XNA    business                     32624.825000  32624.8250

Judging by the differences between mean and median, it's better to go with median.

In [72]:
genders = ['F', 'M']
income_types = ['employee', 'business', 'retiree', 'civil servant', 'entrepreneur', 'student', 'unemployed']

for g in genders:
    for i in income_types:
        median_ti = data.loc[(data['gender'] == g) & (data['income_type'] == i)]['total_income'].median()
        data.loc[(data['gender'] == g) & (data['income_type'] == i), 'total_income'] = data['total_income'].fillna(median_ti)

In [73]:
data.isna().sum()

children            0
days_employed       0
age                 0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        1
purpose             0
dtype: int64

Let's take a look at that remaining row with a missing value

In [74]:
data.loc[data['total_income'].isna()]

children  days_employed   age          education  education_id  \
5936         0    4136.913687  58.0  bachelor's degree             0   

     family_status  family_status_id gender   income_type  debt  total_income  \
5936       married                 0      M  entrepreneur     0           NaN   

                          purpose  
5936  buy residential real estate

This is tricky case: we don't have enough data to get a median value for a male entrepreneur, and we only have one other (female) entrepreneur in our dataset.

In [75]:
data.loc[data['income_type'] == 'entrepreneur']

children  days_employed   age          education  education_id  \
5936          0    4136.913687  58.0  bachelor's degree             0   
18697         0     520.848083  27.0  bachelor's degree             0   

           family_status  family_status_id gender   income_type  debt  \
5936             married                 0      M  entrepreneur     0   
18697  civil partnership                 1      F  entrepreneur     0   

       total_income                      purpose  
5936            NaN  buy residential real estate  
18697     79866.103             having a wedding

So the female entrepreneur is twice as young as the male one, and one thing they have in common apart from their occupation is having a bachelor's degree. We don't have much more data besides that, but the female entrepreneur's total income actually supports our earlier hunch that an entrepreneur would typically have a higher income than a business owner. So I suggest that we go with this assumption and give the male entrepreneur the same total_income. Since it's just one row, we can do this manually.

In [76]:
data.loc[data['income_type'] == 'entrepreneur', 'total_income'] = 79866.103

In [77]:
# Just to check that it worked:
data.isna().sum()

children            0
days_employed       0
age                 0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

Yay!

### Conclusion

So by going over each column from the beginning looking at value_counts, we discovered that there were missing values in days_employed as well as in total_income. There were also the hidden missing values for age – zeros, and one missing value for gender, marked as XNA. In the case of gender, I decided it best to just leave it in place, because filling in that value based on other data would seem to be pure guesswork. On second reflection, remembering the proportion of females to males in our dataset, I think the only other option would be to just assume it's female – but it too would be a stretch. 

For age, days_employed and total_income I had to rely on other data to fill in the missing values. It could be argued that the missing values in age are not that important to the dataset in terms of size, but it was still good practice. It also helped me notice the difference in data between females and males, which is important to consider. 

In the case of days_employed (as with total_income), the amount of rows with missing values was 2174, which is just over 10% of the total amount of rows. Considering that both of these are not pertinent to the main questions of the project task, someone could possibly argue in favour of dropping them. But at the same time, these same rows contain 10% of those who have previously defaulted on their debts – and this column, in turn, is essential to our project's task. So this should tell us that dropping these rows is not a good option.

To fill in the missing values for days_employed I used median values of days_employed depending on gender, age and income_type. The reason for using age is pretty obvious – we don't want to end up with more days_employed than "days lived", so it's important to control for that. By considering gender, we accounted for the fact that females in the same occupation and age seem to have spent a few days less employed – this could happen for a number of reasons such as more common maternity leave. And by controlling for income_type, we additionally accounted for the differences in days_employed that are observed between business owners, civil servants, employees and retirees. Retirees especially seems to have a well-defined range of days_employed, therefore controlling for this should help keep our data consistent.

Even though the missing values for total_income and days_employed occured in the same rows, these two are an example of categories that don't really affect one another, and we saw this in the data. It seems to suggest that total_income records yearly income, which rather depends on the income_type as well as gender, and less so on age. While the gender pay gap that we saw reflects some pretty global societal issues, it's also important for keeping the data consistent. Controlling for income_type, in turn, helped us spot the difference between 'business' and 'entrepreneur', even though there are only two of the latter type in our dataset.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
   I really like your approach to data processing! You use in-depth methods of analysis, well done!
</div>       

### Data type replacement

As we can see below, and as we can remember from looking at specific columns, the three columns where we would like to replace data type to make it more convenient are days_employed, age and total_income. Each of them came with values as floating point numbers, which really doesn't make sense for days_employed and age, and is not that important for total income in this case. So let's change all of them to integers. Since they are already numeric values, we can use astype() function to convert them to integers.

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     21525 non-null  float64
 2   age               21525 non-null  float64
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(3), int64(4), object(5)
memory usage: 2.0+ MB


In [79]:
data['days_employed'] = data['days_employed'].astype(int)
data['age'] = data['age'].astype(int)
data['total_income'] = data['total_income'].astype(int)

In [80]:
# Checking to see if it worked
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   children          21525 non-null  int64 
 1   days_employed     21525 non-null  int64 
 2   age               21525 non-null  int64 
 3   education         21525 non-null  object
 4   education_id      21525 non-null  int64 
 5   family_status     21525 non-null  object
 6   family_status_id  21525 non-null  int64 
 7   gender            21525 non-null  object
 8   income_type       21525 non-null  object
 9   debt              21525 non-null  int64 
 10  total_income      21525 non-null  int64 
 11  purpose           21525 non-null  object
dtypes: int64(7), object(5)
memory usage: 2.0+ MB


<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
     Please note that 64 bits is an excessive amount of space for storing your features.  Here you can read more about data type optimization: <br><a>https://medium.com/@vincentteyssier/optimizing-the-size-of-a-pandas-dataframe-for-low-memory-environment-5f07db3d72e</a>
</div> 

In [81]:
data.head(10)

children  days_employed  age            education  education_id  \
0         1           8437   42    bachelor's degree             0   
1         1           4024   36  secondary education             1   
2         0           5623   33  Secondary Education             1   
3         3           4124   32  secondary education             1   
4         0          14177   53  secondary education             1   
5         0            926   27    bachelor's degree             0   
6         0           2879   43    bachelor's degree             0   
7         0            152   50  SECONDARY EDUCATION             1   
8         2           6929   35    BACHELOR'S DEGREE             0   
9         0           2188   41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0         40620   
1            married                 0      F    employee     0         17932   
2            married                 0      M    employee     0         23341   
3            married                 0      M    employee     0         42820   
4  civil partnership                 1      F     retiree     0         25378   
5  civil partnership                 1      M    business     0         40922   
6            married                 0      F    business     0         38484   
7            married                 0      M    employee     0         21731   
8  civil partnership                 1      F    employee     0         15337   
9            married                 0      M    employee     0         23108   

                               purpose  
0                purchase of the house  
1                         car purchase  
2                purchase of the house  
3              supplementary education  
4                    to have a wedding  
5                purchase of the house  
6                 housing transactions  
7                            education  
8                     having a wedding  
9  purchase of the house for my family

Beautiful ^^.

### Conclusion

We could guess as to why these values came as floats in the first place, but there's not much value to them being floats – they are not scientific calculations or any kind of metrics or even prices, where we would need that precision. With these values, it's easier to operate with nice, round values.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    Yes, that's right. You correctly converted the days_employed and income columns to int format 😊</div>   

### Processing duplicates

Therer are two main columnds where we need to deal with duplicates. These are 'education' and 'purpose'. We know this from before, when we went over each column and looked at the value count. Let's look at 'education' first.

### Processing duplicates in 'education'

In [82]:
data['education'].value_counts()

secondary education    13750
bachelor's degree       4718
SECONDARY EDUCATION      772
Secondary Education      711
some college             668
BACHELOR'S DEGREE        274
Bachelor's Degree        268
primary education        250
Some College              47
SOME COLLEGE              29
PRIMARY EDUCATION         17
Primary Education         15
graduate degree            4
Graduate Degree            1
GRADUATE DEGREE            1
Name: education, dtype: int64

So here we have the same categories written the same way but in different casings (some all lowercase, some all uppercase and some capitalized first letters). Since this is a relatively simple case, it is appropriate to solve it 'by hand', converting all to lowercase. We can check afterwards if its value_count corresponds to that of 'education_id'.

In [83]:
data['education'] = data['education'].str.lower()

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    Very well that you converted the columns to lower case using <code>str.lower()</code></div>  

In [84]:
data['education'].value_counts()

secondary education    15233
bachelor's degree       5260
some college             744
primary education        282
graduate degree            6
Name: education, dtype: int64

In [85]:
# checking that it corresponds to 'education_id'
data['education_id'].value_counts()

1    15233
0     5260
2      744
3      282
4        6
Name: education_id, dtype: int64

That was not very hard, but now we can also use the education column to group our data in new ways if needed.

### Processing duplicates in 'purpose'

Let's take a close look.

In [86]:
data['purpose'].value_counts()

wedding ceremony                            797
having a wedding                            777
to have a wedding                           774
real estate transactions                    676
buy commercial real estate                  664
buying property for renting out             653
housing transactions                        653
transactions with commercial real estate    651
purchase of the house                       647
housing                                     647
purchase of the house for my family         641
construction of own property                635
property                                    634
transactions with my real estate            630
building a real estate                      626
buy real estate                             624
building a property                         620
purchase of my own house                    620
housing renovation                          612
buy residential real estate                 607
buying my own car                       

So it looks like we can safely unify values under all the different wordings for having a wedding ceremony, as well as for car purchase and for education loans. We could use stemming for this, since it should be enough to capture stems of words like 'wedding', 'car' and 'education/educated', but in this case it is even sufficient to use a simple for loop with the 'in' functionality. Housing is a bit trickier, since there are two different purposes – essentially a business-type loan for real estate transactions (buying up office space or property to rent) and something like asking for a mortgage to get a house to live in.

For housing the different key words like house or property are so thoroughly mixed in the different wording, that it's easier (and quicker) to just manually make the lists containing what we deem to denote commercial and residential real estate, and go over them with a loop checking if the purpose equals that, and then brining it to one form.

We can do it in one scoop.

In [87]:
commercial = ['real estate transactions',
              'buy commercial real estate',
              'housing transactions',
              'buying property for renting out',
              'transactions with commercial real estate']
residential = ['purchase of the house',
               'housing',
               'purchase of the house for my family',
               'construction of own property',
               'property',
               'transactions with my real estate',
               'building a real estate',
               'buy real estate',
               'building a property',
               'purchase of my own house',
               'housing renovation', 
               'buy residential real estate']

for c in commercial:
    for purpose in data['purpose']:
        if c == purpose:
            data['purpose'] = data['purpose'].replace(purpose, 'commercial real estate')
            
for r in residential:
    for purpose in data['purpose']:
        if r == purpose:
            data['purpose'] = data['purpose'].replace(purpose, 'housing')

for purpose in data['purpose']:
    if 'wedding' in purpose:
        data['purpose'] = data['purpose'].replace(purpose, 'wedding ceremony')
    elif 'car' in purpose:
        data['purpose'] = data['purpose'].replace(purpose, 'car purchase')
    elif 'educat' in purpose or 'university' in purpose:
        data['purpose'] = data['purpose'].replace(purpose, 'education')

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
 
The `lemmatization` or `stemming` method is also suitable for this purpose :)</div> 

In [88]:
data['purpose'].value_counts()

housing                   7543
car purchase              4315
education                 4022
commercial real estate    3297
wedding ceremony          2348
Name: purpose, dtype: int64

Nice!

### Conclusion

So in some categoris we had no duplicates – like in family status, which was helpful. But we had a lot entries that denote the same loan purpose or the same education background. Education was a bit easier to deal with technically – it was enough to just bring all values to lowercase to have them normalised – now they are distinct categorical values meaning different things, which is much better. We can see clearly how many have which education.

Same thing with loan purpose, even though it was a bit trickier, since the values that potentially mean the same thing were much more varied in writing. It could be the result of a customer stating the purpose of the loan or a bank clerk entering the data manually every time. It could be useful to apply stemming or lemmatization techniques in order to deal with these values, but honestly it seemed like for the purpose of this dataset, and looking over value_counts, it was much quicker to do this one 'by hand' – and it worked.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
   Your method is correct and you have written the function correctly to categorise the purpose of the loan. </div>   


### Categorizing Data

Looking ahead at the project's main questions, I would argue that our main concern for the task would be to create new general categories such as kids/no kids based on the children column, married/not married based on family status as well as income range groups based on the total_income column. We don't need to do anything else to the purpose column since it's already broken down into clear categories.

That will help us calculate the 'crude' default rate in answer to each of the four questions ('crude' if we just compare the default rate, for example, for kids versus no kids), and then look at the more granular differences between the values (for example, the number of chidren from 1 to 5).

But for the sake of practice and also making our data more reusable and pleasant to look at, I would also suggest creating two additional categories: work experience (such as '0-2 years', 2-5 years', etc.) based on days_employed, and age groups based on age. Let's start with those two.

Before categorizing into age groups, it's useful to look at the distribution, which we can also very handily lay out by age in ascending order.

In [89]:
data['age'].value_counts().sort_index()

19     14
20     51
21    111
22    183
23    254
24    264
25    357
26    408
27    493
28    503
29    545
30    540
31    560
32    510
33    581
34    603
35    617
36    555
37    538
38    625
39    573
40    657
41    612
42    597
43    513
44    547
45    497
46    475
47    480
48    538
49    508
50    514
51    448
52    484
53    459
54    479
55    443
56    487
57    460
58    461
59    444
60    397
61    355
62    352
63    269
64    265
65    194
66    183
67    167
68     99
69     85
70     65
71     58
72     33
73      8
74      6
75      1
Name: age, dtype: int64

Now let's create a new column with age groups. I propose a simple categorization here. Since we shouldn't have anyone under 18 asking for a loan, I'm going to put them into a separate category, and then split the rest into roughly what corresponds to 'students + graduates', 'young professionals', 'mid-level professionals', 'experienced' and 'seniors'.

In [90]:
def make_age_group(age):

    if age < 0 or pd.isna(age):
        return 'NA'
    elif age < 18:
        return 'under 18'
    elif 18 <= age < 25:
        return '18-24'
    elif 25 <= age < 35:
        return '25-34'
    elif 35 <= age < 50:
        return '35-49'
    elif 50 <= age < 65:
        return '50-64'
    elif age >= 65:
        return '65+'
    
data['age_group'] = data['age'].apply(make_age_group)

Let's see the result:

In [91]:
data['age_group'].value_counts().sort_index()

18-24     877
25-34    5100
35-49    8332
50-64    6317
65+       899
Name: age_group, dtype: int64

Nice. Now to 'work experience'. The categories here are arbitrary, of course, and they correspon to what seems to corrrespond to levels of experience like 'unexperienced/starting out', 'junior', 'mid-level', 'experienced', 'senioe', 'weathered', 'seen things', etc. :) 

In [92]:
def make_work_exp_group(de):

    if de/365 < 1:
        return '0-1 years'
    elif 1 <= de/365 < 3:
        return '1-3 years'
    elif 3 <= de/365 < 5:
        return '3-5 years'
    elif 5 <= de/365 < 10:
        return '5-10 years'
    elif 10 <= de/365 < 20:
        return '10-20 years'
    elif 20 <= de/365 < 30:
        return '20-30 years'
    elif de/365 >= 30:
        return '30+ years'
    
data['work_experience'] = data['days_employed'].apply(make_work_exp_group)

Let's check out the resulting distribution for these groups

In [93]:
data['work_experience'].value_counts().sort_index()

0-1 years      1828
1-3 years      4093
10-20 years    2451
20-30 years     580
3-5 years      3704
30+ years      4034
5-10 years     4835
Name: work_experience, dtype: int64

Hmm. It turned out an almost even split for the majority of the groups, countring several thousand people per group each, except for the 20-30 years category. Also, the sort_index seems to be reading '3-5 years' as following '20-30', maybe because it reads the first digit only, but that's not such a big issue.

Next, let me categorize into kids/no kids. Everyone with more than 0 kids will have 'kids' status, everyone with 0 kids will have 'no kids'.

In [94]:
def make_kids_status(kids):
    if kids == 0:
        return 'no kids'
    else: 
        return 'kids'
    
data['kids'] = data['children'].apply(make_kids_status)

In [95]:
# Let's have a look
data['kids'].value_counts()

no kids    14149
kids        7376
Name: kids, dtype: int64

In [96]:
data['children'].value_counts()

0    14149
1     4865
2     2131
3      330
4       41
5        9
Name: children, dtype: int64

Looks good.

Now let's create another simple separation into married / not married. Everyone who is not 'married' will simply become 'not married'.

In [97]:
def make_marital_status(status):
    if status == 'married':
        return 'married'
    else:
        return 'not married'
    
data['marital_status'] = data['family_status'].apply(make_marital_status)

In [98]:
# Let's have a look
data['marital_status'].value_counts()

married        12380
not married     9145
Name: marital_status, dtype: int64

In [99]:
data['family_status'].value_counts()

married              12380
civil partnership     4177
unmarried             2813
divorced              1195
widow / widower        960
Name: family_status, dtype: int64

Looks right.

Next up is categories for total income. First, let's look at the distribution. Since there many different values, it's easier to use the describe() method to get a sense of what's going on.

In [100]:
data['total_income'].describe()

count     21525.000000
mean      26435.137933
std       15707.161634
min        3306.000000
25%       17247.000000
50%       23034.000000
75%       31491.000000
max      362496.000000
Name: total_income, dtype: float64

Let me split them up into five categories: less than 10000, 10000-20000, 20000-35000, 35000-70000, and 70000+ (remembering our assumption that the total income is per year). These categories sounds like the kind of income ranges typically associated with low income, low-paid work, a junior/entry level professional, and then up the career ladder, plus everything that exceeds an income typical for a senior specialist in a major company.

In [101]:
def make_income_level_group(income):
    if income < 10000:
        return 'less than 10,000'
    elif 10000 <= income < 20000:
        return '10,000-20,000'
    elif 20000 <= income < 35000:
        return '20,000-35000'
    elif 35000 <= income < 70000:
        return '35,000-70,000'
    elif income >= 70000:
        return '70,000+'
    
data['income_level'] = data['total_income'].apply(make_income_level_group)

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b><br>
    To categorise the income, I can also suggest using the <code>qcut()</code> method, it will indicate the quartile boundaries, which helps to divide the data into equal parts. And equal parts are more convenient to compare with each other :) 

This link can be useful:

https://www.geeksforgeeks.org/how-to-use-pandas-cut-and-qcut/</div>

In [102]:
data['income_level'].value_counts().sort_index()

10,000-20,000       6795
20,000-35000        9735
35,000-70,000       3690
70,000+              379
less than 10,000     926
Name: income_level, dtype: int64

It worked! Let's just see how it looks when we print out the table.

In [103]:
data.head(15)

children  days_employed  age            education  education_id  \
0          1           8437   42    bachelor's degree             0   
1          1           4024   36  secondary education             1   
2          0           5623   33  secondary education             1   
3          3           4124   32  secondary education             1   
4          0          14177   53  secondary education             1   
5          0            926   27    bachelor's degree             0   
6          0           2879   43    bachelor's degree             0   
7          0            152   50  secondary education             1   
8          2           6929   35    bachelor's degree             0   
9          0           2188   41  secondary education             1   
10         2           4171   36    bachelor's degree             0   
11         0            792   40  secondary education             1   
12         0          14921   65  secondary education             1   
13         0           1846   54         some college             2   
14         0           1844   56    bachelor's degree             0   

        family_status  family_status_id gender income_type  debt  \
0             married                 0      F    employee     0   
1             married                 0      F    employee     0   
2             married                 0      M    employee     0   
3             married                 0      M    employee     0   
4   civil partnership                 1      F     retiree     0   
5   civil partnership                 1      M    business     0   
6             married                 0      F    business     0   
7             married                 0      M    employee     0   
8   civil partnership                 1      F    employee     0   
9             married                 0      M    employee     0   
10            married                 0      M    business     0   
11            married                 0      F    employee     0   
12  civil partnership                 1      M     retiree     0   
13            married                 0      F    employee     0   
14  civil partnership                 1      F    business     1   

    total_income                 purpose age_group work_experience     kids  \
0          40620                 housing     35-49     20-30 years     kids   
1          17932            car purchase     35-49     10-20 years     kids   
2          23341                 housing     25-34     10-20 years  no kids   
3          42820               education     25-34     10-20 years     kids   
4          25378        wedding ceremony     50-64       30+ years  no kids   
5          40922                 housing     25-34       1-3 years  no kids   
6          38484  commercial real estate     35-49      5-10 years  no kids   
7          21731               education     50-64       0-1 years  no kids   
8          15337        wedding ceremony     35-49     10-20 years     kids   
9          23108                 housing     35-49      5-10 years  no kids   
10         18230                 housing     35-49     10-20 years     kids   
11         12331  commercial real estate     35-49       1-3 years  no kids   
12         20918        wedding ceremony       65+       30+ years  no kids   
13         20873            car purchase     50-64      5-10 years  no kids   
14         26420                 housing     50-64      5-10 years  no kids   

   marital_status   income_level  
0         married  35,000-70,000  
1         married  10,000-20,000  
2         married   20,000-35000  
3         married  35,000-70,000  
4     not married   20,000-35000  
5     not married  35,000-70,000  
6         married  35,000-70,000  
7         married   20,000-35000  
8     not married  10,000-20,000  
9         married   20,000-35000  
10        married  10,000-20,000  
11        married  10,000-20,000  
12    not married   20,000-35000  
13        married   20,

Nice!

### Conclusion

The original dataset would be hard to use if wanted to analyse something by, say, total income, work experience in days or even age. Grouping data by those values would give us too big a distribution. But when categorized like above (a total of 5 new columns were added), we can potentially tweak our data in any way we want to get a better sense of how income depends on age group, for example, or to find out the relationship between marital status and age, income and education, etc... But let's limit ourselves to the task at hand.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    Good work! 👍 I like that you use our own functions to categorize people by different parameters.</div> 

## Answer these questions

- Is there a relation between having kids and repaying a loan on time?

Pivot tables can be used to answer this, and the following, questions. I'll use 'age' for values as a neutral kinds of value that we don't use to answer other questions, and 'count' as aggfunc. (Using 'sum' with a quantitative value like age would mess up the result).

In [104]:
data_pivot_kids = data.pivot_table(index = 'kids', columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_kids

debt         0     1    All
kids                       
kids      6698   678   7376
no kids  13086  1063  14149
All      19784  1741  21525

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
   It's great that you're using a pivot table to display the information you need 👍 </div>

Very compact! Now we can create an extra column to the right to calculate the default rate. The default rate can be calculated by taking the amount who've defaulted (under '1' column) for each group (kids and no kids) and dividing it by the total amount of people in that group (helpfully present under 'All' thanks to the margins parameter). We can also multiply it by 100 for clarity.

In [105]:
data_pivot_kids['default_rate'] = (data_pivot_kids[1] / data_pivot_kids['All']) * 100

In [106]:
data_pivot_kids

debt         0     1    All  default_rate
kids                                     
kids      6698   678   7376      9.191974
no kids  13086  1063  14149      7.512898
All      19784  1741  21525      8.088269

<div style="border:solid orange 2px; padding: 20px"> <b>Remarks:</b>

 To avoid making additional calculations for the debtors' share column, I can give you a hint on how to generate a summary table quickly. The <code>columns</code> parameter should be omitted, the <code>values</code> parameter should be set to the debt column, and the <code>aggfunc</code> parameter should be set to the function list ['count', 'sum', 'mean']. The result will be three columns: the total number of borrowers, the number of debtors and the proportion of debtors.
    

 </div> 

We can see now that the default rate for the dataset as a whole is roughly 8%. It looks like people who have children are a bit more likely to default on their loan: roughly 9,2% of them have done so in the past. Those who don't have children are less likely to do so: the default rate for this group is 7,5%.

Just in case, I've answered the question taking its wording very literally – therefore kids/no kids. But it's really interesting to see if the default rate is different for people who have kids – does it depend on the number of children? We still have that original column with the number of kids, so let's find out!

In [107]:
data_pivot_children = data.pivot_table(index = 'children', columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_children

debt            0       1    All
children                        
0         13086.0  1063.0  14149
1          4420.0   445.0   4865
2          1929.0   202.0   2131
3           303.0    27.0    330
4            37.0     4.0     41
5             9.0     NaN      9
All       19784.0  1741.0  21525

In [108]:
data_pivot_children['default_rate'] = (data_pivot_children[1] / data_pivot_children['All']) * 100
data_pivot_children

debt            0       1    All  default_rate
children                                      
0         13086.0  1063.0  14149      7.512898
1          4420.0   445.0   4865      9.146968
2          1929.0   202.0   2131      9.479118
3           303.0    27.0    330      8.181818
4            37.0     4.0     41      9.756098
5             9.0     NaN      9           NaN
All       19784.0  1741.0  21525      8.088269

### Conclusion

On the surface, it looks like (for this dataset) the more kids – the lower the default rate. At least we see that tendency judging by the group with 3 children. Of course, the families with 4 kids don't provide a good statistical sample to make any conclusion about the relationship between the number of children and the default rate: the number of such families is only 37. Same for families with 5 kids: only 9 of them (and no defaults). I would imagine that in real life there could be a negative relationship between the number of children and the default rate for rich families, and the reverse for low-income families. 

As for the answer to this question, we do have a large enough sample of families with 1 and 2 kids to conclude that, indeed the there is a positive relationship between default rate and having children.

- Is there a relation between marital status and repaying a loan on time?

To answer this question, let me repeat the process: first take a look at the difference for married / not married, and then look at the breakdown by family status.

In [109]:
data_pivot_marital_status = data.pivot_table(index = 'marital_status', columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_marital_status

debt                0     1    All
marital_status                    
married         11449   931  12380
not married      8335   810   9145
All             19784  1741  21525

Calculate the default rate:

In [110]:
data_pivot_marital_status['default_rate'] = (data_pivot_marital_status[1] / data_pivot_marital_status['All']) * 100
data_pivot_marital_status

debt                0     1    All  default_rate
marital_status                                  
married         11449   931  12380      7.520194
not married      8335   810   9145      8.857299
All             19784  1741  21525      8.088269

Interesting, so whereas having kids is associated with a higher default rate, being married does the opposite. Even though usually married couples tend to eventually have kids. What if we digress and see what's going on, if we account for both marital status and having kids?

In [111]:
data_pivot_married_kids = data.pivot_table(index = ['marital_status', 'kids'], columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_married_kids

debt                        0     1    All
marital_status kids                       
married        kids      4465   415   4880
               no kids   6984   516   7500
not married    kids      2233   263   2496
               no kids   6102   547   6649
All                     19784  1741  21525

In [112]:
data_pivot_married_kids['default_rate'] = (data_pivot_married_kids[1] / data_pivot_married_kids['All']) * 100
data_pivot_married_kids

debt                        0     1    All  default_rate
marital_status kids                                     
married        kids      4465   415   4880      8.504098
               no kids   6984   516   7500      6.880000
not married    kids      2233   263   2496     10.536859
               no kids   6102   547   6649      8.226801
All                     19784  1741  21525      8.088269

Interesting! It looks like the majority of those who are married (in our dataset) don't have children, and this group has a significantly lower default rate, below 7%, and that's what must drag the overall married default rate down. Whereas those who are married and have children, have a default rate that's even slightly above our dataset's average. Those who are not marrie and have kids are the most likely to default, it seems. Also, not having kids in a marriage speaks to higher financial dependency than not having kids and not being married...oh wait, we got that from the first pivot table...

Lastly, let's have a look at the breakdown by family status.

In [113]:
data_pivot_family_status = data.pivot_table(index = 'family_status', columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_family_status

debt                   0     1    All
family_status                        
civil partnership   3789   388   4177
divorced            1110    85   1195
married            11449   931  12380
unmarried           2539   274   2813
widow / widower      897    63    960
All                19784  1741  21525

In [114]:
data_pivot_family_status['default_rate'] = (data_pivot_family_status[1] / data_pivot_family_status['All']) * 100
data_pivot_family_status

debt                   0     1    All  default_rate
family_status                                      
civil partnership   3789   388   4177      9.288963
divorced            1110    85   1195      7.112971
married            11449   931  12380      7.520194
unmarried           2539   274   2813      9.740491
widow / widower      897    63    960      6.562500
All                19784  1741  21525      8.088269

Huh, so those who've been through a divorce have a lower default rate, than those still married. The lowest default rate is for widows and widowers. This also shows that it was likely the right call to put the civil partners into 'not married' category when categorizing the data by family status, because otherwise it could skew the nice default rate for married.

### Conclusion

So we've seen that the married ones tend to default less on average, although not significantly. This tells us that marriage in general is a sign of finanical dependency. This makes sense and tells us that our data is in order – marriage typically reflects some level of commitment – at least to another human. We see further proof of that when we look at the difference in default rate between married with children and not married with children.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
   Thank you for using such in-depth methods of analysis in your research.</div>   

- Is there a relation between income level and repaying a loan on time?

In [115]:
data_pivot_income_level = data.pivot_table(index = 'income_level', columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_income_level

debt                  0     1    All
income_level                        
10,000-20,000      6218   577   6795
20,000-35000       8919   816   9735
35,000-70,000      3422   268   3690
70,000+             357    22    379
less than 10,000    868    58    926
All               19784  1741  21525

In [116]:
data_pivot_income_level['default_rate'] = (data_pivot_income_level[1] / data_pivot_income_level['All']) * 100
data_pivot_income_level

debt                  0     1    All  default_rate
income_level                                      
10,000-20,000      6218   577   6795      8.491538
20,000-35000       8919   816   9735      8.382126
35,000-70,000      3422   268   3690      7.262873
70,000+             357    22    379      5.804749
less than 10,000    868    58    926      6.263499
All               19784  1741  21525      8.088269

In [117]:
# let's sort it by default_rate for clarity
data_pivot_income_level.sort_values('default_rate', ascending = False)

debt                  0     1    All  default_rate
income_level                                      
10,000-20,000      6218   577   6795      8.491538
20,000-35000       8919   816   9735      8.382126
All               19784  1741  21525      8.088269
35,000-70,000      3422   268   3690      7.262873
less than 10,000    868    58    926      6.263499
70,000+             357    22    379      5.804749

That's interesting. We see the general tendency: higher income is associated with a lower defalt rate, but we also see that the group with lowest income (below 10,000 per year) has the second lowest default rate. Perhaps they've taken out smaller loans? Or they can happen to be people who are transitioning to a new job or are supported by relatives.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    Thank you for your bright idea. Very well! 🙂 </div>  

### Conclusion

Our data makes sense, for the most part. It reflects the expected trend of higher income being associated with a lower default rate. Those in the highest earning category have only defaulted in 5,8% of the cases. While those in the middle groups, and who indeed make up most of the data entries, have the default rate slighly above average.

My advice would be that it's relatively safe to assume repayment for higher income groups, since the trend is clear across income levels (despite the highest-earning group comprising the smallest statistical sample). The default rate of 6,2% for the lowest-income group should be treated with caution, however, and that group should be investigated further. In any case, it is also a much smaller data sample compared to the other income level groups.

- How do different loan purposes affect on-time repayment of the loan?

In [118]:
data_pivot_purpose = data.pivot_table(index = 'purpose', columns = 'debt', values = 'age', aggfunc = 'count', margins = True)
data_pivot_purpose

debt                        0     1    All
purpose                                   
car purchase             3912   403   4315
commercial real estate   3043   254   3297
education                3652   370   4022
housing                  7015   528   7543
wedding ceremony         2162   186   2348
All                     19784  1741  21525

In [119]:
data_pivot_purpose['default_rate'] = (data_pivot_purpose[1] / data_pivot_purpose['All']) * 100
data_pivot_purpose

debt                        0     1    All  default_rate
purpose                                                 
car purchase             3912   403   4315      9.339513
commercial real estate   3043   254   3297      7.703973
education                3652   370   4022      9.199403
housing                  7015   528   7543      6.999867
wedding ceremony         2162   186   2348      7.921635
All                     19784  1741  21525      8.088269

In [120]:
data_pivot_purpose.sort_values(by = 'default_rate', ascending = False)

debt                        0     1    All  default_rate
purpose                                                 
car purchase             3912   403   4315      9.339513
education                3652   370   4022      9.199403
All                     19784  1741  21525      8.088269
wedding ceremony         2162   186   2348      7.921635
commercial real estate   3043   254   3297      7.703973
housing                  7015   528   7543      6.999867

Different financial commitments behind taking out the loan fare differently, as we can see from the default rates by purpose. It looks like car purchases are the most unreliable in terms of the probability of non-repayment, at 9.3%. Education comes second, which is somewhat surprising, and wedding ceremony comes third. It looks like it did make sense in the end to separate commercial real estate dealings from people trying to get a house for themselves – we can see how the default rate for them is different, with a difference of roughly 0.7% in favour of just housing.

### Conclusion

So we can see that the goal of taking out a loan can indeed be a predictor of whether you'll be able to repay it. One is most likely to default on a loan when needing it to buy a car, and quite likely when needing the money to pay for education. This last one is a surprising result for me, because intuitively it would seem that people who are taking out a loan to invest in their own 'human capital' have got to be the most promising of the bunch (in terms of financial dependency), so there must be reasons why this is not the case. This could be a reflection of macroeconomic reality to some degree, when a job market in a specific area is overly saturated or there is a recession and many graduates end up without a job. In the U.S., for example, education loans are notoriously crippling, and people end paying these out over many years or even decades – indeed, on some terms, they may even default on them after an expiration deadline.

The wedding ceremony result is a bit surprising from a subjective point of view, because in many eastern european countries a lot of people tend to take out massive loans for the festivities, which they cannot afford – it's a well-documented phenomenon. So I was expecting the default rate there to be higher, but I'm glad to be proven wrong. Somewhat surpisingly, people who take out loans to get their own house have turned out to be the most reliable in our dataset, considering this kind of expenditure has got be the largest one among those spent on personal needs. By way of an educated guess, I'd say this could be due to the fact, that one has to show more 'down payment', so to speak, in advance in order to be assessed as likely to pay our quarterly or monthly mortgage installments on time, and so have more income or savings or a good track record beforehand. Commercial housing which is essentially more of a business loan is a close second, which could tell us that people who come forward having thought through their business scheme can be more relied upon to repay that loan (for the most part).


<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
    Well done for detailed answering!</div> 

## General conclusion

The dataset that was provided didn't have any explicit duplicate values, and only had a chunk of explicitly missing values, that occured in the same rows for days_employed and total_income. Since total_income was pertinent to one of the questions, it had to be dealth with. By examining the data I realized that total_income depended for the most part on the income_type, so I used that in order to fill that in with median values. Thanks to the breadth of the data that I had, I was able to see that it's important to just have a general look at the values first and to play around with the dataset. This made me think twice before just filling in the missing data with median values based on, say, everyone's income, because I saw that it was different depending on gender, among other things. This is a fruitful observation that must have helped in not skewing the resulting stats too much. 

Another issue was the days_employed, which was not helpfully presented, and turned to have a chunk of data that was corrupted, and must have been imported in hours, while the rest of the values had a minus sign. Even though this column wasn't instrumental to the questions, it was helpful to get it in order. Indeed, as a result of further categorizing that data, if we make a pivot table, we will see some substantial differences based on length of work experience. 

I would suggest to the client to consider carefully which factors to take into account when creating the credit rating score. Even though some of the data that we had, like days_employed, might seem irrelevant to the task at hand, it may in fact be helpful. Another thing I would suggest to do in the future is try to collect more data on different working experience as well as income type groups, so we have more instances of every group and can make more statistically sound conclusions for them.

<div style="border:solid green 2px; padding: 20px"> <b>Success:</b><br>
   Thanks for the detailed conclusions, they are logically proven and make it easy to understand what you researched in your project. And, you are very good at making assumptions based on the available data, which makes your research more in-depth 😊
</div> 

## Project Readiness Checklist

Put 'x' in the completed points. Then press Shift + Enter.

- [x]  file open;
- [x]  file examined;
- [x]  missing values defined;
- [x]  missing values are filled;
- [x]  an explanation of which missing value types were detected;
- [x]  explanation for the possible causes of missing values;
- [x]  an explanation of how the blanks are filled;
- [x]  replaced the real data type with an integer;
- [x]  an explanation of which method is used to change the data type and why;
- [x]  duplicates deleted;
- [x]  an explanation of which method is used to find and remove duplicates;
- [x]  description of the possible reasons for the appearance of duplicates in the data;
- [x]  data is categorized;
- [x]  an explanation of the principle of data categorization;
- [x]  an answer to the question "Is there a relation between having kids and repaying a loan on time?";
- [x]  an answer to the question " Is there a relation between marital status and repaying a loan on time?";
- [x]   an answer to the question " Is there a relation between income level and repaying a loan on time?";
- [x]  an answer to the question " How do different loan purposes affect on-time repayment of the loan?"
- [x]  conclusions are present on each stage;
- [x]  a general conclusion is made.